Update python_workflow_test.yml
Extract prefect output around traceback

diff --git a/.github/workflows/python_workflow_test.yml b/.github/workflows/python_workflow_test.yml
--- a/.github/workflows/python_workflow_test.yml
+++ b/.github/workflows/python_workflow_test.yml
@@ -80,10 +80,14 @@ jobs:
       - name: Prefect SPIKE then EMG test
         shell: bash
         working-directory: /home/exouser/Desktop/blech_clust
-        run: conda run -n blech_clust python pipeline_testing/prefect_pipeline.py --spike-emg 2>&1 |
-          tee ~/Desktop/blech_clust/github.log;
-          if grep -q "ERROR" ~/Desktop/blech_clust/github.log;
-                            then echo "ERROR detected by bash"; exit 1; fi
+        run:  conda run -n blech_clust python pipeline_testing/prefect_pipeline.py --spike-emg 2>&1 |
+              tee ~/Desktop/blech_clust/github.log;
+              if grep -q "Traceback" ~/Desktop/blech_clust/github.log; then
+                awk '/Traceback (most recent call last):/{print "Traceback found"; for(i=NR-10;i<=NR+50;i++) print lines[i]; exit} {lines[NR]=$0}' ~/Desktop/blech_clust/github.log
+              fi
+              if grep -q "ERROR" ~/Desktop/blech_clust/github.log; then
+                echo "ERROR detected by bash"; exit 1;
+              fi
   EMG-Only-Install:
     runs-on: self-hosted
     needs: Spike-EMG-Install
@@ -96,9 +100,13 @@ jobs:
         shell: bash
         working-directory: /home/exouser/Desktop/blech_clust
         run: conda run -n blech_clust python pipeline_testing/prefect_pipeline.py -e 2>&1 |
-          tee ~/Desktop/blech_clust/github.log;
-          if grep -q "ERROR" ~/Desktop/blech_clust/github.log;
-                            then echo "ERROR detected by bash"; exit 1; fi
+              tee ~/Desktop/blech_clust/github.log;
+              if grep -q "Traceback" ~/Desktop/blech_clust/github.log; then
+                awk '/Traceback (most recent call last):/{print "Traceback found"; for(i=NR-10;i<=NR+50;i++) print lines[i]; exit} {lines[NR]=$0}' ~/Desktop/blech_clust/github.log
+              fi
+              if grep -q "ERROR" ~/Desktop/blech_clust/github.log; then
+                echo "ERROR detected by bash"; exit 1;
+              fi
   Spike-EMG:
     runs-on: self-hosted
     needs: Preamble
@@ -112,9 +120,13 @@ jobs:
         shell: bash
         working-directory: /home/exouser/Desktop/blech_clust
         run: conda run -n blech_clust python pipeline_testing/prefect_pipeline.py --spike-emg 2>&1 |
-          tee ~/Desktop/blech_clust/github.log;
-          if grep -q "ERROR" ~/Desktop/blech_clust/github.log;
-                            then echo "ERROR detected by bash"; exit 1; fi
+              tee ~/Desktop/blech_clust/github.log;
+              if grep -q "Traceback" ~/Desktop/blech_clust/github.log; then
+                awk '/Traceback (most recent call last):/{print "Traceback found"; for(i=NR-10;i<=NR+50;i++) print lines[i]; exit} {lines[NR]=$0}' ~/Desktop/blech_clust/github.log
+              fi
+              if grep -q "ERROR" ~/Desktop/blech_clust/github.log; then
+                echo "ERROR detected by bash"; exit 1;
+              fi
   EMG-Only:
     runs-on: self-hosted
     needs: Spike-EMG
@@ -128,6 +140,12 @@ jobs:
         shell: bash
         working-directory: /home/exouser/Desktop/blech_clust
         run: conda run -n blech_clust python pipeline_testing/prefect_pipeline.py -e 2>&1 |
-          tee ~/Desktop/blech_clust/github.log;
-          if grep -q "ERROR" ~/Desktop/blech_clust/github.log;
-                            then echo "ERROR detected by bash"; exit 1; fi
+              tee ~/Desktop/blech_clust/github.log;
+              if grep -q "Traceback" ~/Desktop/blech_clust/github.log; then
+                awk '/Traceback (most recent call last):/{print "Traceback found"; for(i=NR-10;i<=NR+50;i++) print lines[i]; exit} {lines[NR]=$0}' ~/Desktop/blech_clust/github.log1
+              fi
+              if grep -q "ERROR" ~/Desktop/blech_clust/github.log; then
+                echo "ERROR detected by bash"; exit 1;
+              fi
+              if grep -q "ERROR" ~/Desktop/blech_clust/github.log;
+                                then echo "ERROR detected by bash"; exit 1; fi
