refactor(workflow): streamline error handling in CI pipelines
- Removed inline `awk` script for extracting tracebacks and replaced it with a dedicated script `extract_traceback.sh`.
- Consolidated error handling to utilize the external script for better maintainability and readability.
- Ensured consistent error detection and reporting across different jobs in the workflow.

diff --git a/.github/workflows/python_workflow_test.yml b/.github/workflows/python_workflow_test.yml
--- a/.github/workflows/python_workflow_test.yml
+++ b/.github/workflows/python_workflow_test.yml
@@ -82,11 +82,10 @@ jobs:
         working-directory: /home/exouser/Desktop/blech_clust
         run:  conda run -n blech_clust python pipeline_testing/prefect_pipeline.py --spike-emg 2>&1 |
               tee ~/Desktop/blech_clust/github.log;
-              if grep -q "Traceback" ~/Desktop/blech_clust/github.log; then
-                awk '/Traceback (most recent call last):/{print "Traceback found"; for(i=NR-10;i<=NR+50;i++) print lines[i]; exit} {lines[NR]=$0}' ~/Desktop/blech_clust/github.log
-              fi
               if grep -q "ERROR" ~/Desktop/blech_clust/github.log; then
-                echo "ERROR detected by bash"; exit 1;
+                echo "ERROR detected by bash";
+                ./pipeline_testing/extract_traceback.sh ~/Desktop/blech_clust/github.log;
+                exit 1;
               fi
   EMG-Only-Install:
     runs-on: self-hosted
@@ -101,11 +100,10 @@ jobs:
         working-directory: /home/exouser/Desktop/blech_clust
         run: conda run -n blech_clust python pipeline_testing/prefect_pipeline.py -e 2>&1 |
               tee ~/Desktop/blech_clust/github.log;
-              if grep -q "Traceback" ~/Desktop/blech_clust/github.log; then
-                awk '/Traceback (most recent call last):/{print "Traceback found"; for(i=NR-10;i<=NR+50;i++) print lines[i]; exit} {lines[NR]=$0}' ~/Desktop/blech_clust/github.log
-              fi
               if grep -q "ERROR" ~/Desktop/blech_clust/github.log; then
-                echo "ERROR detected by bash"; exit 1;
+                echo "ERROR detected by bash";
+                ./pipeline_testing/extract_traceback.sh ~/Desktop/blech_clust/github.log;
+                exit 1;
               fi
   Spike-EMG:
     runs-on: self-hosted
@@ -121,11 +119,10 @@ jobs:
         working-directory: /home/exouser/Desktop/blech_clust
         run: conda run -n blech_clust python pipeline_testing/prefect_pipeline.py --spike-emg 2>&1 |
               tee ~/Desktop/blech_clust/github.log;
-              if grep -q "Traceback" ~/Desktop/blech_clust/github.log; then
-                awk '/Traceback (most recent call last):/{print "Traceback found"; for(i=NR-10;i<=NR+50;i++) print lines[i]; exit} {lines[NR]=$0}' ~/Desktop/blech_clust/github.log
-              fi
               if grep -q "ERROR" ~/Desktop/blech_clust/github.log; then
-                echo "ERROR detected by bash"; exit 1;
+                echo "ERROR detected by bash";
+                ./pipeline_testing/extract_traceback.sh ~/Desktop/blech_clust/github.log;
+                exit 1;
               fi
   EMG-Only:
     runs-on: self-hosted
@@ -141,9 +138,8 @@ jobs:
         working-directory: /home/exouser/Desktop/blech_clust
         run: conda run -n blech_clust python pipeline_testing/prefect_pipeline.py -e 2>&1 |
               tee ~/Desktop/blech_clust/github.log;
-              if grep -q "Traceback" ~/Desktop/blech_clust/github.log; then
-                awk '/Traceback (most recent call last):/{print "Traceback found"; for(i=NR-10;i<=NR+50;i++) print lines[i]; exit} {lines[NR]=$0}' ~/Desktop/blech_clust/github.log1
-              fi
               if grep -q "ERROR" ~/Desktop/blech_clust/github.log; then
-                echo "ERROR detected by bash"; exit 1;
+                echo "ERROR detected by bash";
+                ./pipeline_testing/extract_traceback.sh ~/Desktop/blech_clust/github.log;
+                exit 1;
               fi
