Fix emg test

diff --git a/.github/workflows/python_workflow_test.yml b/.github/workflows/python_workflow_test.yml
--- a/.github/workflows/python_workflow_test.yml
+++ b/.github/workflows/python_workflow_test.yml
@@ -15,19 +15,28 @@ jobs:
       - name: Prefect SPIKE only test
         shell: bash
         working-directory: /home/abuzarmahmood/Desktop/blech_clust
-        run: python pipeline_testing/prefect_pipeline.py -s --raise-exception 2>&1 | tee ~/Desktop/blech_clust/github.log;
-          if grep -q "ERROR" ~/Desktop/blech_clust/github.log; then echo "ERROR detected by bash"; exit 1; fi
-          #   EMG-Only:
-          #     runs-on: self-hosted
-          #     steps:
-          #       - name: Prefect EMG only test
-          #         shell: bash
-          #         working-directory: /home/abuzarmahmood/Desktop/blech_clust
-          #         run: python pipeline_testing/prefect_pipeline.py -e --raise-exception
-          #   Spike-EMG:
-          #     runs-on: self-hosted
-          #     steps:
-          #       - name: Prefect SPIKE then EMG test
-          #         shell: bash
-          #         working-directory: /home/abuzarmahmood/Desktop/blech_clust
-          #         run: python pipeline_testing/prefect_pipeline.py --spike-emg --raise-exception
+        run: python pipeline_testing/prefect_pipeline.py -s 2>&1 |\
+          tee ~/Desktop/blech_clust/github.log;
+          if grep -q "ERROR" ~/Desktop/blech_clust/github.log;\
+                            then echo "ERROR detected by bash"; exit 1; fi
+  EMG-Only:
+    runs-on: self-hosted
+    steps:
+      - name: Prefect EMG only test
+        shell: bash
+        working-directory: /home/abuzarmahmood/Desktop/blech_clust
+        run: python pipeline_testing/prefect_pipeline.py -e 2>&1 |\
+          tee ~/Desktop/blech_clust/github.log;
+          if grep -q "ERROR" ~/Desktop/blech_clust/github.log;\
+                            then echo "ERROR detected by bash"; exit 1; fi
+  Spike-EMG:
+    runs-on: self-hosted
+    steps:
+      - name: Prefect SPIKE then EMG test
+        shell: bash
+        working-directory: /home/abuzarmahmood/Desktop/blech_clust
+        run: python pipeline_testing/prefect_pipeline.py --spike-emg 2>&1 |\
+          tee ~/Desktop/blech_clust/github.log;
+          if grep -q "ERROR" ~/Desktop/blech_clust/github.log;\
+                            then echo "ERROR detected by bash"; exit 1; fi
+
